UdemyAspNetCoreMembership-master/UdemyAspNetCoreMembership-master/UdemyIdentity/Controllers/AdminController.cs
using Mapster;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UdemyIdentity.Models;
using UdemyIdentity.ViewModes;

namespace UdemyIdentity.Controllers
{
    //[Authorize(Roles = "admin")]
    public class AdminController : BaseController
    {
        public AdminController(UserManager<AppUser> userManager, RoleManager<AppRole> roleManager) : base(userManager, null, roleManager)
        {
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Claims()
        {
            return View(User.Claims.ToList());
        }

        public IActionResult RoleCreate()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RoleCreate(RoleViewModel roleViewModel)
        {
            AppRole role = new AppRole();
            role.Name = roleViewModel.Name;
            IdentityResult result = roleManager.CreateAsync(role).Result;

            if (result.Succeeded)

            {
                return RedirectToAction("Roles");
            }
            else
            {
                AddModelError(result);
            }

            return View(roleViewModel);
        }

        public IActionResult Roles()
        {
            return View(roleManager.Roles.ToList());
        }

        public IActionResult Users()
        {
            return View(userManager.Users.ToList());
        }

        public IActionResult RoleDelete(string id)
        {
            AppRole role = roleManager.FindByIdAsync(id).Result;
            if (role != null)
            {
                IdentityResult result = roleManager.DeleteAsync(role).Result;
            }

            return RedirectToAction("Roles");
        }

        public IActionResult RoleUpdate(string id)
        {
            AppRole role = roleManager.FindByIdAsync(id).Result;

            if (role != null)
            {
                return View(role.Adapt<RoleViewModel>());
            }

            return RedirectToAction("Roles");
        }

        [HttpPost]
        public IActionResult RoleUpdate(RoleViewModel roleViewModel)
        {
            AppRole role = roleManager.FindByIdAsync(roleViewModel.Id).Result;

            if (role != null)
            {
                role.Name = roleViewModel.Name;
                IdentityResult result = roleManager.UpdateAsync(role).Result;

                if (result.Succeeded)
                {
                    return RedirectToAction("Roles");
                }
                else
                {
                    AddModelError(result);
                }
            }
            else
            {
                ModelState.AddModelError("", "Güncelleme işlemi başarısız oldu.");
            }

            return View(roleViewModel);
        }

        public IActionResult RoleAssign(string id)
        {
            TempData["userId"] = id;
            AppUser user = userManager.FindByIdAsync(id).Result;

            ViewBag.userName = user.UserName;

            IQueryable<AppRole> roles = roleManager.Roles;

            List<string> userroles = userManager.GetRolesAsync(user).Result as List<string>;

            List<RoleAssignViewModel> roleAssignViewModels = new List<RoleAssignViewModel>();

            foreach (var role in roles)
            {
                RoleAssignViewModel r = new RoleAssignViewModel();
                r.RoleId = role.Id;
                r.RoleName = role.Name;
                if (userroles.Contains(role.Name))
                {
                    r.Exist = true;
                }
                else
                {
                    r.Exist = false;
                }
                roleAssignViewModels.Add(r);
            }

            return View(roleAssignViewModels);
        }

        [HttpPost]
        public async Task<IActionResult> RoleAssign(List<RoleAssignViewModel> roleAssignViewModels)
        {
            AppUser user = userManager.FindByIdAsync(TempData["userId"].ToString()).Result;

            foreach (var item in roleAssignViewModels)
            {
                if (item.Exist)

                {
                    await userManager.AddToRoleAsync(user, item.RoleName);
                }
                else
                {
                    await userManager.RemoveFromRoleAsync(user, item.RoleName);
                }
            }

            return RedirectToAction("Users");
        }

        public async Task<IActionResult> ResetUserPassword(string id)
        {
            AppUser user = await userManager.FindByIdAsync(id);

            PasswordResetByAdminViewModel passwordResetByAdminViewModel = new PasswordResetByAdminViewModel();
            passwordResetByAdminViewModel.UserId = user.Id;

            return View(passwordResetByAdminViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> ResetUserPassword(PasswordResetByAdminViewModel passwordResetByAdminViewModel)
        {
            AppUser user = await userManager.FindByIdAsync(passwordResetByAdminViewModel.UserId);

            string token = await userManager.GeneratePasswordResetTokenAsync(user);

            await userManager.ResetPasswordAsync(user, token, passwordResetByAdminViewModel.NewPassword);

            await userManager.UpdateSecurityStampAsync(user);

            //securitystamp degerini  update etmezsem kullanıcı eski şifresiyle sitemizde dolaşmaya devam eder ne zaman çıkış yaparsa ozaman tekrar yeni şifreyle girmek zorunda
            //eger update edersen kullanıcı  otomatik olarak  sitemize girdiği zaman login ekranına yönlendirilecek.

            //Identity Mimarisi cookie tarafındaki securitystamp ile veritabanındaki security stamp değerini her 30 dakikada bir kontrol eder. Kullanıcı eski şifreyle en fazla server da session açıldıktan sonra 30 dakkika gezebilir. Bunu isterseniz 1 dakkikaya indirebilirsiniz. ama tavsiye edilmez. her bir dakika da  her kullanıcı için veritabanı kontrolü  yük getirir.

            return RedirectToAction("Users");
        }
    }
}

UdemyAspNetCoreMembership-master/UdemyAspNetCoreMembership-master/UdemyIdentity/Controllers/MemberController.cs
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using UdemyIdentity.Enums;
using UdemyIdentity.Models;
using UdemyIdentity.ViewModes;

namespace UdemyIdentity.Controllers
{
    [Authorize]
    public class MemberController : BaseController
    {
        public MemberController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager) : base(userManager, signInManager)
        {
        }

        public IActionResult Index()
        {
            AppUser user = CurrentUser;
            UserViewModel userViewModel = user.Adapt<UserViewModel>();

            return View(userViewModel);
        }

        public IActionResult UserEdit()
        {
            AppUser user = CurrentUser;

            UserViewModel userViewModel = user.Adapt<UserViewModel>();

            ViewBag.Gender = new SelectList(Enum.GetNames(typeof(Gender)));

            return View(userViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> UserEdit(UserViewModel userViewModel, IFormFile userPicture)
        {
            ModelState.Remove("Password");
            ViewBag.Gender = new SelectList(Enum.GetNames(typeof(Gender)));
            if (ModelState.IsValid)
            {
                AppUser user = CurrentUser;

                string phone = userManager.GetPhoneNumberAsync(user).Result;

                if (phone != userViewModel.PhoneNumber)
                {
                    if (userManager.Users.Any(u => u.PhoneNumber == userViewModel.PhoneNumber))
                    {
                        ModelState.AddModelError("", "Bu telefon numarası başka üye tarafından kullanılmaktadır.");
                        return View(userViewModel);
                    }
                }

                if (userPicture != null && userPicture.Length > 0)
                {
                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(userPicture.FileName);

                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/UserPicture", fileName);

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await userPicture.CopyToAsync(stream);

                        user.Picture = "/UserPicture/" + fileName;
                    }
                }

                user.UserName = userViewModel.UserName;
                user.Email = userViewModel.Email;
                user.PhoneNumber = userViewModel.PhoneNumber;

                user.City = userViewModel.City;

                user.BirthDay = userViewModel.BirthDay;

                user.Gender = (int)userViewModel.Gender;

                IdentityResult result = await userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    await userManager.UpdateSecurityStampAsync(user);
                    await signInManager.SignOutAsync();
                    await signInManager.SignInAsync(user, true);

                    ViewBag.success = "true";
                }
                else
                {
                    AddModelError(result);
                }
            }

            return View(userViewModel);
        }

        public IActionResult PasswordChange()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PasswordChange(PasswordChangeViewModel passwordChangeViewModel)
        {
            if (ModelState.IsValid)
            {
                AppUser user = CurrentUser;

                bool exist = userManager.CheckPasswordAsync(user, passwordChangeViewModel.PasswordOld).Result;

                if (exist)
                {
                    IdentityResult result = userManager.ChangePasswordAsync(user, passwordChangeViewModel.PasswordOld, passwordChangeViewModel.PasswordNew).Result;

                    if (result.Succeeded)
                    {
                        await userManager.UpdateSecurityStampAsync(user);
                        await signInManager.SignOutAsync();

                        await signInManager.PasswordSignInAsync(user, passwordChangeViewModel.PasswordNew, true, false);

                        ViewBag.success = "true";
                    }
                    else
                    {
                        AddModelError(result);
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Eski şifreniz yanlış");
                }
            }

            return View(passwordChangeViewModel);
        }

        public void LogOut()
        {
            signInManager.SignOutAsync();
        }

        public IActionResult AccessDenied(string ReturnUrl)
        {
            if (ReturnUrl.ToLower().Contains("violencegage"))
            {
                ViewBag.message = "Erişmeye çalıştığınız sayfa şiddet videoları içerdiğinden dolayı 15 yaşında büyük olmanız gerekmektedir";
            }
            else if (ReturnUrl.ToLower().Contains("ankarapage"))
            {
                ViewBag.message = "Bu sayfaya sadece şehir alanı ankara olan kullanıcılar erişebilir";
            }
            else if (ReturnUrl.ToLower().Contains("exchange"))
            {
                ViewBag.message = "30 günlük ücretsiz deneme hakkınız sona ermiştir.";
            }
            else
            {
                ViewBag.message = "Bu sayfaya erişim izniniz yoktur. Erişim izni almak için site yöneticisiyle görüşünüz";
            }

            return View();
        }

        [Authorize(Roles = "manager,admin")]
        public IActionResult Manager()
        {
            return View();
        }

        [Authorize(Roles = "editor,admin")]
        public IActionResult Editor()
        {
            return View();
        }

        [Authorize(Policy = "AnkaraPolicy")]
        public IActionResult AnkaraPage()
        {
            return View();
        }

        [Authorize(Policy = "ViolencePolicy")]
        public IActionResult ViolencePage()
        {
            return View();
        }

        public async Task<IActionResult> ExchangeRedirect()
        {
            bool result = User.HasClaim(x => x.Type == "ExpireDateExchange");

            if (!result)
            {
                Claim ExpireDateExchange = new Claim("ExpireDateExchange", DateTime.Now.AddDays(30).Date.ToShortDateString(), ClaimValueTypes.String, "Internal");

                await userManager.AddClaimAsync(CurrentUser, ExpireDateExchange);

                await signInManager.SignOutAsync();
                await signInManager.SignInAsync(CurrentUser, true);
            }

            return RedirectToAction("Exchange");
        }

        [Authorize(Policy = "ExchangePolicy")]
        public IActionResult Exchange()
        {
            return View();
        }
    }
}

UdemyAspNetCoreMembership-master/UdemyAspNetCoreMembership-master/UdemyIdentity/Views/Member/AccessDenied.cshtml
@{
    ViewData["Title"] = "AccessDenied";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}

<div class="alert alert-danger">
    @ViewBag.message
</div>

UdemyAspNetCoreMembership-master/UdemyAspNetCoreMembership-master/UdemyIdentity/Views/Member/AnkaraPage.cshtml
@{
    ViewData["Title"] = "AnkaraPage";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}

<h1>Ankara sayfasına hoş geldiniz..</h1>

UdemyAspNetCoreMembership-master/UdemyAspNetCoreMembership-master/UdemyIdentity/Views/Member/Editor.cshtml
@{
    ViewData["Title"] = "Editor";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}

<h1>Editor sayfasına hoş geldiniz.</h1>

UdemyAspNetCoreMembership-master/UdemyAspNetCoreMembership-master/UdemyIdentity/Views/Member/Exchange.cshtml
@{
    ViewData["Title"] = "Exchange";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}

<h3>30 gün boyunca ücretsiz olarak bu sayfayı görebilirsiniz.</h3>

UdemyAspNetCoreMembership-master/UdemyAspNetCoreMembership-master/UdemyIdentity/Views/Member/Index.cshtml
@model UserViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}
<h3 class="text-center">Kullanıcı Bilgileri</h3>
<div class="row">
    <div class="col-sm-3">
        <img style="width:100%; height:100%" src="@Model.Picture" />
    </div>
    <div class="col-sm-9">

        <table class="table table-bordered table-striped">
            <tr>
                <th>Kullanıcı ismi</th>
                <td>@Model.UserName</td>
            </tr>
            <tr>
                <th>E-posta</th>
                <td>@Model.Email</td>
            </tr>

            <tr>
                <th>Telefon no</th>
                <td>@Model.PhoneNumber</td>
            </tr>
            <tr>
                <th>City</th>
                <td>
                    @if (!String.IsNullOrEmpty(Model.City))
                    {
                        @Model.City
                    }
                    else

                    {
                        <span>belirtilmemiş</span>
                    }
                </td>
            </tr>
            <tr>
                <th>Doğum tarihi</th>
                <td>

                    @if (Model.BirthDay != null)
                    {
                        @Model.BirthDay?.ToShortDateString()
                    }
                    else

                    {
                        <span>belirtilmemiş</span>
                    }
                </td>
            </tr>

            <tr>
                <th>Cinsiyet</th>
                <td>@Model.Gender</td>
            </tr>
        </table>
    </div>
</div>

UdemyAspNetCoreMembership-master/UdemyAspNetCoreMembership-master/UdemyIdentity/Views/Member/Manager.cshtml
@{
    ViewData["Title"] = "Manager";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}

<h1>Yönetici sayfasına hoş geldiniz</h1>

UdemyAspNetCoreMembership-master/UdemyAspNetCoreMembership-master/UdemyIdentity/Views/Member/PasswordChange.cshtml
@model UdemyIdentity.ViewModes.PasswordChangeViewModel

@{
    ViewData["Title"] = "PasswordChange";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}

<h2>Şifre Değiştirme</h2>
<hr />

@if (ViewBag.success == "true")
{
    <div class="alert alert-info">
        Şifreniz Güncellenmiştir.
    </div>

}
else
{
    <div class="row">
        <div class="col-md-12">
            <form asp-action="PasswordChange">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="PasswordOld" class="control-label"></label>
                    <input asp-for="PasswordOld" class="form-control" />
                    <span asp-validation-for="PasswordOld" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PasswordNew" class="control-label"></label>
                    <input asp-for="PasswordNew" class="form-control" />
                    <span asp-validation-for="PasswordNew" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PasswordConfirm" class="control-label"></label>
                    <input asp-for="PasswordConfirm" class="form-control" />
                    <span asp-validation-for="PasswordConfirm" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Şifre değiştir" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
}

UdemyAspNetCoreMembership-master/UdemyAspNetCoreMembership-master/UdemyIdentity/Views/Member/UserEdit.cshtml
@model UdemyIdentity.ViewModes.UserViewModel

@{
    ViewData["Title"] = "UserEdit";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}

<h2>Bilgi Güncelleme</h2>
@if (ViewBag.success == "true")
{
    <div class="alert alert-info">
        <span>Bilgileriniz güncellenmiştir.</span>
    </div>
}
<div class="row">
    <div class="col-md-12">
        <form asp-action="UserEdit" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="BirthDay" class="control-label"></label>
                <input asp-for="BirthDay" class="form-control" />
                <span asp-validation-for="BirthDay" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <select class="form-control" asp-for="Gender" asp-items="@ViewBag.Gender"></select>
            </div>

            <div class="form-group">

                <label class="control-label">Resim</label>
                <input class="form-control" type="file" name="userPicture" />
            </div>

            <div class="form-group">
                <input type="submit" value="Güncelle" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

UdemyAspNetCoreMembership-master/UdemyAspNetCoreMembership-master/UdemyIdentity/Views/Member/ViolencePage.cshtml
@{
    ViewData["Title"] = "ViolencePage";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}

<h1>Bu sayfa şiddet videoları içerir.</h1>

UdemyAspNetCoreMembership-master/UdemyAspNetCoreMembership-master/UdemyIdentity/Views/Member/_MemberLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">Bıdıbıdı.com</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">

                <ul class="navbar-nav">

                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Member">Üye Ana Sayfa</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-info" asp-action="Index" asp-controller="Admin">Admin ana sayfa</a>
                    </li>

                    <li class="nav-item">
                        <a class="btn btn-info" asp-action="Editor" asp-controller="Member">Editor ana sayfa</a>
                    </li>

                    <li class="nav-item">
                        <a class="btn btn-info" asp-action="Manager" asp-controller="Member">Manager ana sayfa</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container" style="margin-top:10px;">
        <div class="row">
            <div class="col-md-8">
                @RenderBody()
            </div>
            <div class="col-md-4">
                <h3>Menü</h3>

                <a class="btn btn-danger btn-block" asp-action="AnkaraPage" asp-controller="Member">Ankara sayfa</a>

                <a class="btn btn-danger btn-block" asp-action="ViolencePage" asp-controller="Member">Şiddet içeren sayfa</a>
                <a class="btn btn-danger btn-block" asp-action="ExchangeRedirect" asp-controller="Member">Borsa bilgileri</a>

                <a class="btn btn-info btn-block" asp-action="PasswordChange" asp-controller="Member">Şifre değiştirme</a>

                <a class="btn btn-info btn-block" asp-action="UserEdit" asp-controller="Member">Bilgi güncelleme</a>

                <a class="btn btn-info btn-block" asp-action="Logout" asp-controller="Member" asp-route-returnUrl="/Home/Index">Çıkış yap</a>
            </div>
        </div>
    </div>
</body>
</html>